package cn.ep.spring.boot.ch03.s05.dao;

import cn.ep.spring.boot.ch03.s05.dto.*;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface CustomerMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    long countByExample(CustomerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    int deleteByExample(CustomerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    List<Customer> selectByExampleWithRowbounds(CustomerCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    List<Customer> selectByExample(CustomerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    Customer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     */
    int updateByPrimaryKey(Customer record);
}